# Copyright (c) 2024 SVCH <svch@seriousaboutsolutions.co.uk>
# SPDX-License-Identifier: MIT
[default]
exclude-files = [
    "src/replacement/template_data/*",
    "amber_out/*",
    "amber_proposals/*",
    "benches_out/*",
]
